<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('team_info')->insert([
            [
                'team_id' => 1,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 2,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 3,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 4,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 5,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 6,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 7,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 8,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 9,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 10,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 11,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 12,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 13,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 14,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 15,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 16,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 17,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 18,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 19,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
            [
                'team_id' => 20,
                'points' => 0,
                'games' => 0,
                'wins' => 0,
                'draws' => 0,
                'loses' => 0,
                'goals' => 0,
                'goals_against' => 0,
                'goal_difference' => 0,
            ],
        ]);
    }
}
